<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "bought_courses".
 *
 * @property int $id
 * @property int $userId
 * @property int $courseId
 * @property int $monthId
 */
class BoughtCourses extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'bought_courses';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['userId', 'courseId', 'monthId'], 'required'],
            [['userId', 'courseId', 'monthId'], 'integer'],
        ];
    }
    public function getUser()
    {
        return $this->hasOne(Users::class, ['id' => 'userId']);
    }
    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'userId' => Yii::t('app', 'User'),
            'courseId' => Yii::t('app', 'Course'),
            'monthId' => Yii::t('app', 'Months'),
        ];
    }
    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
