<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "bought_courses".
 *
 * @property int $id
 * @property int $user
 * @property int $course
 * @property int $mounth
 */
class BoughtCourses extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'bought_courses';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user', 'course', 'mounth'], 'required'],
            [['user', 'course', 'mounth'], 'integer'],
        ];
    }
    public function getUser()
    {
        return $this->hasOne(Users::class, ['id' => 'user']);
    }
    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user' => Yii::t('app', 'User'),
            'course' => Yii::t('app', 'Course'),
            'mounth' => Yii::t('app', 'Mounth'),
        ];
    }
    public function afterFind()
    {
        $this->user = Users::findOne($this->user);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
